---

- name: create directory to save rpm package
  shell: mkdir -p /tmp/rpm
  when: ansible_os_family == "RedHat"

- name: copy docker-ce rpm package
  copy: src={{role_path}}/../../pre-env/k8s-{{kubernetesVersion}} dest=/tmp/rpm
  when: ansible_os_family == "RedHat"


- name: copy repo k8s.repo file to /etc/yum.repos.d
  template: src={{role_path}}/templates/k8s.repo dest=/etc/yum.repos.d/ owner=root group=root
  when: ansible_os_family == "RedHat"

- name: install kubelet kubeadm kubectl
  yum: name=kubelet,kubeadm,kubectl state=latest
  when: ansible_os_family == "RedHat"

- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: systemctl start kubelet && systemctl start kubelet
  shell: systemctl start kubelet && systemctl enable kubelet
